version: '1'

services:
  aashi-springboot-container:
    image: aashi-spring-boot-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/aashi-springboot-container
    ports:
      - "8080-8100:8080"
