apiVersion: apps/v1
kind: Deployment
metadata:
  name: aashi-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aashi-springboot
  template:
    metadata:
      labels:
        app: aashi-springboot
    spec:
      containers:
        - name: springboot
          image: aashi0707/aashi-docker-demo:aashi-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: aashi-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: aashi-springboot
